# Generated by Django 4.2.23 on 2025-07-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menuitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
